### ISSUE TITLE
panic because of missing logger

### ISSUE THREAD

**Issue by cryptix** [pion/quic#35]
using latest master (after #32) in pion/webrtc leads to a crash because the logger isn't setup correctly somehow: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15bc13e]

goroutine 90 [running]:
github.com/pion/quic.(*TransportBase).acceptStreams(0xc0002980a8)
	/Users/cryptix/go/pkg/mod/github.com/pion/quic@v0.1.2-0.20200714121404-405825cda397/transportbase.go:114 +0xee
created by github.com/pion/quic.(*TransportBase).startBase
	/Users/cryptix/go/pkg/mod/github.com/pion/quic@v0.1.2-0.20200714121404-405825cda397/transportbase.go:64 +0x53
exit status 2
```

https://github.com/pion/quic/blob/405825cda397c816d3e82536e138042b7beab0c9/transportbase.go#L114

**Comment by cryptix** [comment]
I'm not yet sure if this needs to be done in webrtc or here in this packet. Investigating.

**Comment by cryptix** [comment]
AFAICT the logging factory was never passed on correctly. Patch incoming.
